### ISSUE TITLE
getPendingNotifications error

### ISSUE THREAD

**Issue by ppcano** [mgcrea/cordova-push-notification#1]
I installed the plugin and working with the Notification API. I didn't have experience before, but it seems the getPendingNotification method is not working ( it returns an empty notiification array ) or perhaps i didn't understand something.

I need to implement a getApplicationIconBadgeNumber to get my app logic working. However,  i think the API could be extended to get notificationCenterMessagesLength to cover more cases.

Let me know if you want me to create the current PR.

**Comment by mgcrea** [comment]
As far as I know, it is not possible to interact with the notification center from an app in iOS.

See this plugin docs :

> getPendingNotifications() should be used when your application starts or become active (from the background) to retrieve notifications that have been pushed while the application was inactive or offline. **For now, it can only retrieve the notification that the user has interacted with while entering the app**. Returned params applicationStateActive & applicationLaunchNotification enables you to filter notifications by type.

**Comment by mgcrea** [comment]
Regarding the `getApplicationIconBadgeNumber` thing, you can create a PR for this and I'll gladly merge it.
