### ISSUE TITLE
Plugin not working with Cordova 2.4.0 due to JSONKit.h missing

### ISSUE THREAD

**Issue by NeilVaidya** [mgcrea/cordova-push-notification#6]
The new version of Cordova 2.4.0 has removed JSONKit so it throws an error that it can't find the import file.

**Comment by patrickhafner** [comment]
just import JSONKit directly in your project and change the line in PushNotification.m to
`#import "JSONKit.h"`

https://github.com/johnezang/JSONKit

**Comment by AndrewJHart** [comment]
Is it better to import JSONkit or just replace cdvjk_JSONString with JSONString?

**Comment by patrickhafner** [comment]
To avoid upcoming issues, just import JSONkit. Didn't test the renaming.

**Comment by marciok** [comment]
Use:  
#import <Cordova/CDVJSON.h>

It work's on 2.5

**Comment by mgcrea** [comment]
Should be fixed with #13
