### ISSUE TITLE
does not work in iphone 3gs

### ISSUE THREAD

**Issue by dbwhddn10** [mgcrea/cordova-push-notification#7]
i have pad 1 & iphone 3gs 

pad 1 is work very well but i phone 3gs not work 

it seems like issue #4 

test cordova version 2.2.0 ~ 2.5.0

**Comment by mgcrea** [comment]
Is it the same exact error message? What is the iOS version?

**Comment by johnpupu** [comment]
I am sure that iphone 3GS is work.
I am using iPhone 3GS to develop.

**Comment by mgcrea** [comment]
Thanks @johnpupu
