### ISSUE TITLE
Display notification in push-notification event

### ISSUE THREAD

**Issue by aerlijman** [mgcrea/cordova-push-notification#8]
First.. thx a lot for this great code! Everything is working perfect. I would like to know if it is possible to display the notification I get when my app is active in the push-notification event like the ones I get when the app is not active. I mean, with the nice banner and info in the notification center. Ideas?
Ariel

**Comment by mgcrea** [comment]
I don't think you can while the application is active. You have to implement something alike inside your application.

**Comment by aerlijman** [comment]
make sense. thx
